### ISSUE TITLE
Correcting const input code

### ISSUE THREAD

**Issue by conniedc1206** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#11]
### Canvas Link

https://learning.flatironschool.com/courses/5192/assignments/185948?module_item_id=413207

### Concern

const input = document.getElementById('button');

### Suggested Changes

The id isn't 'button' , it should be 'input' for this to work. The code that we need to copy and paste from the README/canvas module still has 'button' for the const input

**Comment by professor-ben** [comment]
Fixed in #13
