### ISSUE TITLE
inconsistency with id in test and html file

### ISSUE THREAD

**Issue by Aaidenplays** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#16]
### Canvas Link

https://learning.flatironschool.com/courses/5298/assignments/168040?module_item_id=363097

### Concern

student was failing test because the id that is given on the html element that is being queried by test is set to `button` whereas the test queries for `input` 

FIX: change the id='button'  to id='input' in index.html

### Suggested Changes

FIX: change the id='button'  to id='input' in index.html

**Comment by lizbur10** [comment]
Hi Aaiden! I believe this issue was fixed yesterday. If the student re-clones it, it should work, but please let us know if there's still a problem. 💙
