### ISSUE TITLE
Difference in the Id Name

### ISSUE THREAD

**Issue by ashtontobar** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#17]
In the lesson in Canvas the code includes `const input = document.getElementById("button")` and instructs students to copy & paste the code into the console in the browser and VS Code in order to pass the test. However, the button's Id is "input" in index.html, not "button" so an error pops up. Not sure if this is intentional or not, but wanted to flag it just in case.

**Comment by lizbur10** [comment]
Hi @ashtontobar - thanks for bringing this to our attention. The error has been fixed 💙
