### ISSUE TITLE
addingEventListener() doesn't allow 'click' event to run

### ISSUE THREAD

**Issue by Asarec** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#18]
### Canvas Link

https://learning.flatironschool.com/courses/5639/assignments/179041?confetti=true&submitted=0

### Concern

Code:

```JavaScript
function addingEventListener() {
    const input = document.getElementById('button');

    input.addEventListener('click', () => {
        document.getElementsByTagName('div')[1].remove();
    });
}
```

The above code doesn't run in the browser. However, removing the nested code from the `addingEventListener()` function allows it to run successfully.

**Comment by lizbur10** [comment]
Hi @Asarec ! Sorry to hear you're having problems with this. I am not able to reproduce the issue - when I run the code in the browser it works as expected. It may be that you didn't call the addingEventListener() function before you tried to click the button. Recall that you need to run the function first in order for the event listener to be created.

If you're still having problems with this, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team. 💙
