### ISSUE TITLE
no element button 

### ISSUE THREAD

**Issue by vecter1180** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#19]
### Canvas Link

https://learning.flatironschool.com/courses/5292/assignments/179703?module_item_id=396882

### Concern

There doesn't appear  to be a button element but I might be wrong as I'm still learning 

### Additional Context

const input = document.getElementById('button');
input.addEventListener('click', function() {
  alert('I was clicked!');
});

VM1327:2 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at <anonymous>:2:7

### Suggested Changes

add a button element

**Comment by lizbur10** [comment]
Hi @vecter1180! Sorry to hear you're running into problems with this! I am not able to reproduce the problem so I'm not sure why it isn't working for you. I suggest that you reach out to your instructor or use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in
Canvas to connect with a Technical Coach on the Academic Success Team.

If you still believe that there is something wrong with the code itself, please feel free to reopen this issue 💙
