### ISSUE TITLE
npm test results are broken.

### ISSUE THREAD

**Issue by themanselmo** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> Add a link to the assignment in Canvas here.

## Describe the bug
initial npm test results in this:

$ npm test

> javascript-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json

  1) "before all" hook

  0 passing (7s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at /mnt/d/Programming/FlatironSchool/code/phase0/phase-0-javascript-events-event-listening-lab/node_modules/jsdom/lib/jsdom.js:312:18
      at processTicksAndRejections (node:internal/process/task_queues:78:11)

> Write a clear and concise description of what the bug is. Include the file and
> line number(s) if possible.

## What is the expected behavior?

> Write a clear and concise description of what you expected to happen.

## Screenshots

> If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [x] Linux

## Any additional context?

> Add any other context about the problem here.

**Comment by lizbur10** [comment]
Hi there! I'm closing this issue - please see my response on the issue you posted on the What is a Test Lab 💙
