### ISSUE TITLE
The id of the input on the HTML is not the same as the id the test file expects

### ISSUE THREAD

**Issue by dominickub** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#20]
### Canvas Link

https://learning.flatironschool.com/courses/5631/assignments/175600?module_item_id=385684

### Concern

The id of the input on the HTML is not the same as the id the test file expects. 

### Suggested Changes

In the HTML file (line 20) you can either change the Id of the input element to "input" or you can change the test file (line 7) expected id on the input to "button"

**Comment by lizbur10** [comment]
Hey @dominickub! Thanks for bringing this to our attention! 

This problem was actually fixed a month or so ago, but we didn't update the solution code, so it was still grabbing `#input` instead of `#button`. I have now updated the solution which will hopefully resolve the issue.

Thanks again! 💙
