### ISSUE TITLE
Index.js test has an error

### ISSUE THREAD

**Issue by gebber14** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#23]
### Canvas Link

https://learning.flatironschool.com/courses/5300/assignments/179744?module_item_id=397074

### Concern

There was an error in the test.  It should read: 
input = document.getElementById('button');

### Suggested Changes

There was an error in the test.  It should read: 
input = document.getElementById('button');

**Comment by martinezjf2** [comment]
Great Catch on this. Was just going to open up a ticket on this as well. Thank you!

**Comment by lizbur10** [comment]
Hi @gebber14! Thanks for bringing this to our attention. The error has been fixed 💙
