### ISSUE TITLE
Incorrect element id referenced in code snippet in Canvas

### ISSUE THREAD

**Issue by BigDawg826** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#24]
### Canvas Link

https://my.learn.co/courses/355/assignments/16574?module_item_id=38484

### Concern

Canvas references element id "input" in code snippet and elsewhere.  The correct element id is "button".  It's referenced correctly in the readme.md in GitHub for this lesson. 

_Now when you click inside of input#input, you will get an alert box_.  Should be input#button

### Suggested Changes

const input = document.getElementById('button');

**Comment by lizbur10** [comment]
Hi @BigDawg826 ! Thanks for bringing this to our attention. The lab has been updated to correct this issue, but it was after your course was created in Canvas so unfortunately the update isn't reflected in your course. You can see the corrected version by viewing the lab's README here in GitHub instead.

Apologies for the inconvenience and thanks for contributing to the curriculum 💙
