### ISSUE TITLE
Solution key does not grab the correct id.

### ISSUE THREAD

**Issue by dominickub** [learn-co-curriculum/phase-0-javascript-events-event-listening-lab#25]
### Canvas Link

https://learning.flatironschool.com/courses/4978/assignments/167576?module_item_id=362197

### Concern

The answer solution of the lesson has 

const input = document.querySelector('button')

The id of this element is "input".

### Additional Context

![image](https://user-images.githubusercontent.com/89448197/198859704-35e44ee8-6a47-4896-bd29-78a14e8a3186.png)

### Suggested Changes

1. We can change the answer key to be "input" instead of it saying button. 

or 

2. We can change the id of the button to "button" (this is line 20).

**Comment by lizbur10** [comment]
Hi @dominickub! The solution branch of labs can diverge from the main or master branch over time. The solution branch is a good resource to see other ways to approach a problem, but the main/master branch will have the most up to date tests and instructions. If you run the tests in the master branch with that code, they should pass.

Cheers! 💙
